force-app/main/default/objects/ChattingGroup__c/ChattingGroup__c.object-meta.xml
<CustomObject>
    <description>하나의 채팅방이 된다</description>
    <label>채팅그룹</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>채팅그룹</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ChattingGroup__c/fields/IsPrivate__c.field-meta.xml
<CustomField>
    <fullName>IsPrivate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>비밀 채팅방 활성화</description>
    <label>IsPrivate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChattingGroup__c/fields/Members__c.field-meta.xml
<CustomField>
    <fullName>Members__c</fullName>
    <description>참여자 User Record Id 저장
최대 10명 제한
구분자는 &quot;;&quot;(세미콜론) 으로 한다.</description>
    <label>참여자 recordId</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ChattingGroup__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>10자리 이내 비밀 채팅방 비밀번호</description>
    <label>Password</label>
    <length>10</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/createNewChattingGroupController.cls
public with sharing class createNewChattingGroupController {
    @AuraEnabled
    public static Map<String, Object> searchUsers(String searchText) {
        Map<String, Object> result = new Map<String, Object>();

        try {
            if(String.isBlank(searchText)) throw new SearchException('검색어가 없습니다.');
            searchText = searchText.trim();

            User[] users = [SELECT Id, Name FROM User WHERE Name LIKE :('%'+searchText+'%') ORDER BY Name];
            UserData[] userDatas = new UserData[]{};

            for(User u : users) {
                userDatas.add(new UserData(u).setMark(searchText));
            }

            result.put('users', userDatas);
            result.put('state', 'SUCCESS');

        } catch (Exception e) {
            result.put('state', 'ERROR');
            result.put('message', e.getMessage()+' line: ['+e.getLineNumber()+']');
        }

        return result;
    }

    @AuraEnabled
    public static Map<String, Object> createChat(RecordData submitData) {
        Map<String, Object> result = new Map<String, Object>();
        Savepoint sp = Database.setSavepoint();
        try {
            ChattingGroup__c cg = new ChattingGroup__c();
            cg.Name = submitData.name;
            cg.Password__c = submitData.password;
            cg.Members__c = submitData.members;
            cg.IsPrivate__c = submitData.isPrivate;

            insert cg;

            ChatController.PermissionResult permisstionResult = ChatController.updateChatSharing(
                String.valueOf(cg.Id)
                , submitData.members == null ? new String[]{} : submitData.members.split(';')
            );
            if(permisstionResult.state == 'SUCCESS') {
                result.put('recordId', cg.Id);
                result.put('state', 'SUCCESS');
            } else throw new SharingException(permisstionResult.message);

        } catch (Exception e) {
            Database.rollback(sp);
            result.put('state', 'ERROR');
            result.put('message', e.getMessage()+' line: ['+e.getLineNumber()+']');
        }

        return result;
    }

    class SharingException extends Exception{}
    class SearchException extends Exception{}

    public class UserData {
        @AuraEnabled public String recordId {get;set;}
        @AuraEnabled public String name {get;set;}
        @AuraEnabled public String markerName {get;set;}
        @AuraEnabled public String photoUrl {get;set;}
        public UserData() {}
        public UserData(User u) {
            ConnectApi.Photo photo = ConnectApi.UserProfiles.getPhoto(System.Network.getNetworkId(), u.Id);
            this.photoUrl = photo.smallPhotoUrl;
            this.name = u.Name;
            this.recordId = u.Id;
        }
        
        public UserData setMark(String text) {
            String replaceTarget = '(?i)'+text;
            String marker = '<mark>$0</mark>';
            this.markerName = this.name.replaceAll(replaceTarget, marker);
            return this;
        }
    }

    public class RecordData {
        @AuraEnabled public String name {get;set;}
        @AuraEnabled public String password {get;set;}
        @AuraEnabled public String members {get;set;}
        @AuraEnabled public Boolean isPrivate {get;set;}
    }
}